name: Clang / C++11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make Clang-9/C++11 check
      run: make -C tests CXX=clang++-9 CXXSTD=c++11 check
    
