name: GCC / C++14

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make GCC 8/C++14 check
      run: make -C tests CXX=g++-8 CXXSTD=c++14 check
    
