name: GCC / C++17

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make GCC 8/C++17 check
      run: make CXX=g++-8 CXXSTD=c++17 check
    
